all:
  hosts:
    k8s-master:
      ansible_host: 192.168.44.100

    k8s-worker1:
      ansible_host: 192.168.44.101

    k8s-worker2:
      ansible_host: 192.168.44.102

  children:
    master:
      hosts:
        k8s-master:

    workers:
      hosts:
        k8s-worker1:
        k8s-worker2:
